### ISSUE TITLE
Cannot build kickstart theme

### ISSUE THREAD

**Issue by rylan-michael** [apigee/apigee-devportal-kickstart-drupal#469]
## Description
Using `npm run production` to build a fresh apigee_kickstart theme fails. I believe there are two issues. The bug may have been introduced in the PR #448 specifically commit [d0c3264](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/448/commits/d0c3264e4e65435225adedc7c9f82c56753aff5b).
* The first issue is that --hide-modules has been deprecated. See [Upgrade to Mix 6#Update Your NPM Scripts](https://github.com/JeffreyWay/laravel-mix/blob/628f6062cceb77610b1813e3179abcbd043a4642/UPGRADE.md#update-your-npm-scripts). Laravel upgraded to using Webpack 5.
* The second issue is that once I remove --hide-modules or use `npx mix -p` I run into another issue and I'm not sure what's the cause. My hunch is that it may be related to sass-loader. See [SassError: Can't find stylesheet to import when it contains @forward with _index file #804](https://github.com/webpack-contrib/sass-loader/issues/804)

## Steps to Reproduce
Steps to reproduce the behavior (I'm using ddev and node/npm on my main machine):
1. `composer create-project apigee/devportal-kickstart-project:9.x-dev theme-issue`
2. `ddev config` to setup webroot at web/ and the project type to drupal 9
3. `ddev start`
4. `cd web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart`
5. `npm -v` (returns 7.5.4)
6. `node -v `(returns v15.8.0 but i've also tried with LTS)
7. `npm install --dev`
8. `npm run production`

    ```
    error: unknown option '--hide-modules'
    [webpack-cli] Run 'webpack --help' to see available commands and options
    ```

9. Remove the --hide-modules option from **package.json**
10. Run `npm run production` without the --hide-modules option

    ```
    > NODE_ENV=production node_modules/webpack/bin/webpack.js --progress  --config=node_modules/laravel- 
    mix/setup/webpack.config.js

 	Additional dependencies must be installed. This will only take a moment.

 	Running: npm install postcss@^8.1 --save-dev --legacy-peer-deps

 	Finished. Please run Mix again.
    ```

11. Run `npm run production` again

## Actual Behavior

I get the following error with no modifications on any theme files.

```
> production
> NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

ERROR in ./src/sass/apigee-kickstart.style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
3 │ @import "base/functions";
  │         ^^^^^^^^^^^^^^^^
  ╵
  src/sass/base/_base.scss 3:9              @import
  src/sass/apigee-kickstart.style.scss 3:9  root stylesheet
    at processResult (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/webpack/lib/NormalModule.js:597:19)
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/webpack/lib/NormalModule.js:691:5
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:91131:16)
    at _render_closure1.call$2 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:80007:12)
    at _RootZone.runBinary$3$3 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:27193:18)
    at _FutureListener.handleError$1 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:25721:19)

ERROR in ./src/sass/apigee-kickstart.monetization.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
3 │ @import "base/functions";
  │         ^^^^^^^^^^^^^^^^
  ╵
  src/sass/base/_base.scss 3:9                     @import
  src/sass/apigee-kickstart.monetization.scss 1:9  root stylesheet
    at processResult (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/webpack/lib/NormalModule.js:597:19)
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/webpack/lib/NormalModule.js:691:5
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:91131:16)
    at _render_closure1.call$2 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:80007:12)
    at _RootZone.runBinary$3$3 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:27193:18)
    at _FutureListener.handleError$1 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:25721:19)

ERROR in ./src/sass/apigee-kickstart.monetization.add-credit.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
3 │ @import "base/functions";
  │         ^^^^^^^^^^^^^^^^
  ╵
  src/sass/base/_base.scss 3:9                                @import
  src/sass/apigee-kickstart.monetization.add-credit.scss 1:9  root stylesheet
    at processResult (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/webpack/lib/NormalModule.js:597:19)
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/webpack/lib/NormalModule.js:691:5
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:91131:16)
    at _render_closure1.call$2 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:80007:12)
    at _RootZone.runBinary$3$3 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:27193:18)
    at _FutureListener.handleError$1 (/Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/node_modules/sass/sass.dart.js:25721:19)

3 ERRORS in child compilations
webpack compiled with 6 errors
npm ERR! code 1
npm ERR! path /Users/rylan.mccarty/Documents/theme-issue/web/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart
npm ERR! command failed
npm ERR! command sh -c NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rylan.mccarty/.npm/_logs/2021-04-23T04_08_10_760Z-debug.log
```

**Comment by raakesh-blokhra** [comment]
Assigned to @phdhiren. Hiren please take a look and confirm.
